### PR TITLE
fixes #6 : POST platforms/id/config

### LINKED ISSUE #6: POST platforms/id/config is not functionnal
formating of platform id is missing.

### PR DESCRIPTION
**Pull request by mbredif**
@ldgeo, is that the correct way to fix #6 ?

### CODE REVIEW

**Comment by ldgeo** [comment]
not really, it's more simple, i fixed it with 2de93b2

**Comment by mbredif** [comment]
Not sure, with your fix, the `platform_id` in the request uri (`/platforms/<platform_id>/configs`) is not used at all...
The endpoint should not then be `/configs` rather than `/platforms/<platform_id>/configs` ?

**Comment by ldgeo** [comment]
you're right, i've touched the wrong parameter... but we don't need platform_id as it stands in the URL 
-> branch updated

**Comment by mbredif** [comment]
Now `platform` shows up in `/platforms/configs/<config_id>`  but not in `/platforms/<platform_id>/configs` 

The discrepancy comes from the marshalling [in the latter case](https://github.com/LI3DS/api-li3ds/blob/e517d094f264f40e1ad6e2df06bb16e0c1360d75/api_li3ds/apis/platform.py#L93) but not [in the former](https://github.com/LI3DS/api-li3ds/blob/e517d094f264f40e1ad6e2df06bb16e0c1360d75/api_li3ds/apis/platform.py#L115-L117)

Do you want to shadow the platform as it is already passed by the user in the query or not ? My guess is you want to marshall in any case, and that you need to [add the platform id to the model](https://github.com/LI3DS/api-li3ds/blob/2665a371d35e3b76748526c012da5bd1691739db/api_li3ds/apis/platform.py#L41) if you want to expose it.

**Comment by ldgeo** [comment]
no confusion for me, this is not the same endpoint, why do you need the platform id in /platforms/{id}/configs/ ? 
As you said, you have it in the request.

**Comment by mbredif** [comment]
Ok, I got it. you'd rather minimize communication (do not return the platform id if it was known as part of the query) rather than uniform return values for endpoints returning configs (`/platforms/configs/<config_id>`  and `/platforms/<platform_id>/configs`). Thanks for explaining !

**Pull request merged**
