### PR TITLE
Docker

### PR DESCRIPTION
**Pull request by mbredif**
This is a firqt attempt of a docker container for the li3ds stack.

### CODE REVIEW

**Comment by elemoine** [comment]
Can we just move the Docker-related stuff in a `docker` directory? Feel free to merge when this is done.

**Review by elemoine — APPROVED** [review]

**Comment by mbredif** [comment]
I unfortunately cannot make an automated build work on dockerhub with a dockerfile in a subdirectory : https://hub.docker.com/r/mbredif/api-li3ds/builds/
Do you know how to do it ?

**Comment by elemoine** [comment]
I don't know. What's the problem? Path the Dockerfile itself? Relative paths used in the Dockerfile?

**Comment by mbredif** [comment]
Looks like when I point the build to `docker/Dockerfile` then the context of the build is restricted to the `docker` directory: It does the equivalent of `docker build docker` rather than `docker build -f docker/Dockerfile .`

**Comment by elemoine** [comment]
Ok, feel free to move the Dockerfile back to where it was it you don't find a solution. Sorry for that.

**Comment by mbredif** [comment]
Ok reverting...

**Pull request merged**
