### PR TITLE
Config preview with sensors and labels

### PR DESCRIPTION
**Pull request by mbredif**
This PR is an attempt to address #8 :

- adds a `/platforms/configs/<config_id>/dot` to give access to the raw dot source in order to enable debuging, further manual tweaking or integration with other tools. This is done by factoring out a `platform_config_dot` function.
- the url of the config is added as a comment in the source
- referentials are grouped into sensor subgraphs, showing the sensor `name` and `id`
- transfos also show the `func_name` of their `transfo_type`
- the graph is labelled is with the configuration `name` and `id`, as well as the platform `id`

@ldgeo, I had to modify a bit the SQL queries. They appear to work on my simple tests but I am not sure they are optimal in general.

# Sample PNG output

apili3ds-graph

# Sample DOT output
```
// http://localhost:5000/platforms/configs/5/dot/
digraph config_5 {
	graph [label="Platform 1 : config2_name (5)" overlap=scalexy]
		subgraph cluster_1 {
			graph [label="sensor1_name (1)"]
				1 [label="ref1_name
(1)" color=red]
				2 [label="ref2_name
(2)" color=red]
				3 [label="ref3_name
(3)" color=red]
		}
		subgraph cluster_2 {
			graph [label="sensor2_name (2)"]
				5 [label="ref4_name
(5)" color=red]
				6 [label="ref6_name
(6)" color=black]
		}
			1 -> 2 [label="transfotype1_name
(1)" color=black]
			2 -> 3 [label="transfotype1_name
(2)" color=black]
			5 -> 6 [label="transfotype3_name
(3)" color=black]
			3 -> 5 [label="transfotype3_name
(5)" color=blue]
}
```

### CODE REVIEW

**Comment by ldgeo** [comment]
I've just tested quickly and i'm getting a KeyError in the ``platform_config_dot`` function.
I'll have a look at the sql changes later.

**Comment by ldgeo** [comment]
@mbredif , 2 problems: 

- you considered sensor.id = referential.id, which is not exact. 
- when platform_config id does not exists, it hangs with a KeyError

i made some fixes and merged master with last changes, now everything's fine.

The preview is really nice now thanks !
@mbredif @elemoine if you're ok i'll merge it !

**Review by elemoine — APPROVED** [review]

**Comment by mbredif** [comment]
In the meantime, I was working with the a transfo_tree visualization as well to visualize the import of a blinis using [micmac_li3ds](/LI3DS/micmac_li3ds) and integrated your changes @ldgeo :

- visualisation of the transfo tree imported from a blini
image png 413 x 347 pixels

- visualisation of the configuration and platform manually created around this transfo tree (as this example wraps only this unique transfo_tree, only the caption differs, but it still supports configs with multiple transfo_trees)
image png 413 x 367 pixels

I factored out much of the common code into a new dot.py source file.

@ldgeo, your dot code had redundant subgraphs, as can be seen in the sources ([fixed here](https://github.com/LI3DS/api-li3ds/blob/e92f55c83781494740ee7013b6e257280a650bdb/api_li3ds/dot.py#L31-L32))

**Comment by ldgeo** [comment]
@mbredif thanks there was a bad indentation on ``dot.subgraph(subgraphs[node.sensor])``.
Did you used push --force ? some commits were lost.
I push some style commits.

**Comment by mbredif** [comment]
Sorry for the push force...
And thanks for the styling and refactoring !

**Pull request merged**
